kind: Service
apiVersion: v1
metadata:
  name: etcd.default.svc.cluster.local
spec:
  selector:
    etcd_cluster: example-etcd-cluster
    app: etcd
  ports:
  - protocol: TCP
    port: 2379
    targetPort: 2379
    nodePort: 32379
  type: NodePort