apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    app.kubernetes.io/instance: etcd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: etcd
    app.kubernetes.io/version: v3.4.16
    helm.sh/chart: etcd-0.1.3
spec:
  publishNotReadyAddresses: true
  type: NodePort
  ports:
  - port: 2380
    name: etcd-server
  - port: 2379
    name: etcd-client
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: etcd
    app.kubernetes.io/name: etcd
